version: "3.1"
services:
  sd_webui:
    image: "trihd4500/sd_webui:0.2"
    ports:
      - "7860:7860"
    volumes:
      - ./models:/home/sdWebUi/stable-diffusion-webui/models
      - ./webui-user-cpu.sh:/home/sdWebUi/stable-diffusion-webui/webui-user.sh
      - ./webui.sh:/home/sdWebUi/stable-diffusion-webui/webui.sh
      - ./venv:/home/sdWebUi/stable-diffusion-webui/venv
      - ./repositories:/home/sdWebUi/stable-diffusion-webui/repositories
      - ./extensions:/home/sdWebUi/stable-diffusion-webui/extensions
      - ./outputs:/home/sdWebUi/stable-diffusion-webui/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
